-- AlterTable
ALTER TABLE "Plant" ADD COLUMN     "careTips" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "categoryTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "caution" TEXT,
ADD COLUMN     "difficulty" TEXT,
ADD COLUMN     "family" TEXT,
ADD COLUMN     "featured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "growthRate" TEXT,
ADD COLUMN     "hindiName" TEXT,
ADD COLUMN     "identification" JSONB,
ADD COLUMN     "images" JSONB,
ADD COLUMN     "modernResearch" JSONB,
ADD COLUMN     "partsUsed" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "region" TEXT,
ADD COLUMN     "safetyDosage" JSONB,
ADD COLUMN     "season" TEXT,
ADD COLUMN     "summary" TEXT,
ADD COLUMN     "synonyms" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "tagline" TEXT;
